name: build-hub-image

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4

      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.hub
          push: false

