name: build-images

on:
  push:

jobs:
  docker-hub:
    uses: ./.github/workflows/build-image-template.yml
    secrets:
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      docker-file: Dockerfile.hub
      image-name: softwareimprovementgroup/sigridci:latest

  docker-azure:
    uses: ./.github/workflows/build-image-template.yml
    secrets:
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      docker-file: Dockerfile.Azure
      image-name: softwareimprovementgroup/sigridci:azure

  docker-actions-test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile