name: build-image-template

on:
  workflow_call:
    inputs:
        docker-file:
            required: true
            type: string
        image-name:
            required: true
            type: string
    secrets:
        dockerhub-token:
            required: true
jobs:
  docker-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: "softwareimprovementgroup"
          password: ${{ secrets.dockerhub-token }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          file: ${{ inputs.docker-file }}
          platforms: linux/amd64,linux/arm64
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ inputs.image-name }}
