name: build-images

on:
  push:

jobs:
  docker-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: "softwareimprovementgroup"
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  docker-azure:
    uses: ./.github/workflows/build-image-template.yml
    with:
      docker-file: Dockerfile.Azure
      image-name: softwareimprovementgroup/sigridci:azure
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}

  docker-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile