name: unittests
env:
 BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 

on: 
  push:
    branches:
      - BRANCH_NAME
jobs:
  unittests:
    name: "Python unit tests"
    runs-on: ubuntu-latest
    steps:
      - name: "Check out repository"
        uses: actions/checkout@v3
      - run: "pip3 install -r test/requirements.txt --user"
      - run: "python3 -m unittest"
